name = "MultifileArrays"
uuid = "18a1d154-b244-4181-98dd-8f3786468fa3"
version = "0.1.0"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"

[extensions]
MultifileArraysBlockArrays = "BlockArrays"

[compat]
BlockArrays = "1"
ColorTypes = "0.12"
FileIO = "1"
FixedPointNumbers = "0.8"
ImageIO = "0.6"
SparseArrays = "1"
Test = "1"
julia = "1.10"

[extras]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BlockArrays", "ColorTypes", "FileIO", "FixedPointNumbers", "ImageIO", "Test"]
